### ISSUE TITLE
Issue with `pkgbuild-aur` action

### ISSUE THREAD

**Issue by ReenigneArcher** [zjuyk/archrepo#1]
Issues are not enabled for https://github.com/zjuyk/pkgbuild-aur but considering it points to this repo as a demo, hopefully this is okay to open one here.

Getting a lot of errors and cannot install a dependency.
https://github.com/SunshineStream/Sunshine/runs/6955734550?check_suite_focus=true#step:7:144
```txt
:: Running post-transaction hooks...
(1/9) Creating system user accounts...
(2/9) Updating journal message catalog...
(3/9) Reloading system manager configuration...
Failed to check for chroot() environment: Permission denied
  Skipped: Current root is not booted.
(4/9) Updating udev hardware database...
(5/9) Applying kernel sysctl settings...
Failed to check for chroot() environment: Permission denied
  Skipped: Current root is not booted.
(6/9) Creating temporary files...
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
(7/9) Reloading device manager configuration...
Failed to check for chroot() environment: Permission denied
  Skipped: Device manager is not running.
(8/9) Arming ConditionNeedsUpdate...
(9/9) Reloading system bus configuration...
Failed to check for chroot() environment: Permission denied
  Skipped: Current root is not booted.
 -> Could not find all required packages:
	ffmpeg4.4 (Target)
```

Any idea how to resolve?

**Comment by ReenigneArcher** [comment]
I changed the dependency to `ffmpeg` instead of `ffmpeg4.4` and it got past that error. Perhaps there is a bug when a dependency contains a period (`.`)?

`ffmpeg4.4` is in the Extra repo.

![image](https://user-images.githubusercontent.com/42013603/174488783-c8435a42-e823-41c9-aa19-4e6b9c28249f.png)

Unfortunately this package requires `ffmpeg4.4` and `ffmpeg` will not work right now.

**Comment by zjuyk** [comment]
The upstream docker mirror is not the latest version with latest package index, so it can not find ffmpeg4.4.  Just add `RUN pacman -Syu --noconfirm` in dockerfile to solve this issue

**Comment by ReenigneArcher** [comment]
Thank you... I ended up using another action `hapakaien/archlinux-package-action@v2`, but will keep this one in mind.
